### ISSUE TITLE
action menu tests exceeded timeout of 5000ms

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#1068]
What should be the default timeout for new modules? Maybe 20 seconds?

Should also apply this for other modules.

@genaris can you take a look at this issue?

**Comment by genaris** [comment]
Based on what I've seen in previous OK and NOK CI runs, that default of 5000 ms is at the limit for E2E tests, so that would be the reason why it passes most of the times but not always. I think that 10000 should be enough, but 20000 will be safer. 

In #1069 I've added this to action-menu and question-answer, which also failed a few times in the past. I did the same for tenants module, whose tests had a 2000 second timeout which seems to be not necessary. The test that usually fails from tenants is the sessions E2E one: for that particular case I've incremented default session acquire timeout from 1000 to 10000 ms. 

Hope it works better now!
