### ISSUE TITLE
The typing might be getting overly complicated and hard to read

### ISSUE THREAD

**Issue by jleach** [hyperledger/aries-framework-javascript#1208]
Its getting a little tough to figure out what to import for types and they don't really make sence. For example:

```
        const credentials = await agent.proofs.getRequestedCredentialsForProofRequest({
          proofRecordId: proof.id,
          config: {
            filterByNonRevocationRequirements: false,
          },
        })
```

Return `FormatRetrievedCredentialOptions<[IndyProofFormat]>` where the words are not obvious what's going on. Its a bit tough to figure out what to import to pass that into another fn like:

`const fn = (retrievedCredentials: any) => { do something }` what to import to replace `any` is a little tough. It might be worth rethinking what the word "Format" and "Options" mean in this type.

**Comment by TimoGlastra** [comment]
Thanks for opening this issue @jleach. The typing here is indeed a bit weird. We still need to do some work to align the proofs api with the credentials api and make sure interfaces aren't used on different levels. (this is actually an internal interface, that happens to align with the public interface, but we shouldn't have reused them)

It should probably be called something like `CredentialsForProofRequest` or `RetrievedCredentialsReturn`. Any preference on the names?

In general I try to only infer types instead of manually declaring them.

You could for example do: 

```
type CredentialsForProofRequest  = typeof credentials
```

Which would be the same as `FormatRetrievedCredentialOptions<[IndyProofFormat]>`.

**Comment by TimoGlastra** [comment]
This has been fixed in main. Will introduce again some breaking changes in 0.4.0 but I think types have more straighforward names now
