### ISSUE TITLE
Inconsistency in events emitted between credentials and connections 

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#157]
As a developer I expect the event listeners present on modules and services to be consistent in how they work and when they emit events.

The connections and credentials modules both contain an event listener that emits state changed events when the state of a record changes. E.g. when a credential exchange record transitions from state requested to issued, or when a connection record transitions from response to completed. 

However there is a small inconsistency in when the `StateChanged` event is emitted:
- for connections the event is not emitted on creation (`createInvitation` / `receiveInvitation`)
- for credentials the event is emitted on creation (`createOffer` / `receiveOffer`)

I think it can be helpful to receive a state changed event on creation (state `null` to `...`) so we should probably update the connection event listener to also emit on creation.

**Comment by karimStekelenburg** [comment]
I might be missing something, but I'm noticing another events related inconsistency between [ConnectionsModule](https://github.com/hyperledger/aries-framework-javascript/blob/9cee1bee6d/src/lib/modules/ConnectionsModule.ts) and [CredentialsModule](https://github.com/hyperledger/aries-framework-javascript/blob/9cee1bee6d/src/lib/modules/CredentialsModule.ts).

The `ConnectionsModule` exposes a `events()` method that returns the `ConnectionsService` which allows me to listen for connection changes. When attempting to implement a similar listener for credential changes I noticed `CredentialsModule` does **not** have an `events()` method.

Not sure if this is intentional, but as a developer I'd expect them to work the same.

**Comment by TimoGlastra** [comment]
Closed by #159
