### ISSUE TITLE
Using Aries Javascript Framework on mobile

### ISSUE THREAD

**Issue by icc-romeu** [hyperledger/aries-framework-javascript#182]
Hi all,

I have been following the community efforts to build a Mobile Aries Agent and I am aware of at least 4 implementations on React Native. 

I was wondering whether a RN Indy wrapper like this [https://github.com/AbsaOSS/rn-indy-sdk](https://github.com/AbsaOSS/rn-indy-sdk) could implement the [Wallet Interface](https://github.com/hyperledger/aries-framework-javascript/blob/main/src/lib/wallet/Wallet.ts) and be injected as a dependency for this Aries Framework. Then, a React Native App could import this framework to use it as a Mobile Aries agent. 

I do not really see any problem on that, as plain Javascript can work perfectly as a dependency on React Native, provided the library does not use node-dependent libraries.

**Comment by TimoGlastra** [comment]
Hi @icc-romeu.

We've been working to make Aries Framework JavaScript available in React Native.

We depend on indy, which is a pluggable dependency. So in React Native you can provide indy from rn-indy-sdk instead of the NodeJS variant.

I'll make sure to update the documentation on how to use this with React Native. An example is a mobile app we've been working on written in React Native that depends on this framework: https://github.com/animo/aries-mobile-agent-react-native

There are some problems with React Native and Indy so you should be sure to use a version of React Native <= 0.61.5.

**Comment by icc-romeu** [comment]
Hi @TimoGlastra I was aware of that work there but did not realise that used this framework! 😅 Thanks for the explanation. Keep up that good work!

**Comment by TimoGlastra** [comment]
I've openend #186 to describe how the framework can be used in React Native. I'll also make sure to update the docs in the mobile agent repository
