### ISSUE TITLE
Improve dependency injection

### ISSUE THREAD

**Issue by jakubkoci** [hyperledger/aries-framework-javascript#211]
As a developer, I want to dynamically inject and use various framework modules and their classes, so that I can preserve the open-closed principle when I want to enhance or change the agent's behavior based on a custom implementation.

Currently, we have dependencies hardcoded in Agent class and wired together manually. If someone wants to update or change the behavior of the framework they must change the Agent class directly.

We consider the use of some existing JS dependency injection solutions:
- [Nest.js DI](https://docs.nestjs.com/), [Minimal implementation example](https://github.com/jakubkoci/nest-di)
- [Awilix](https://github.com/jeffijoe/awilix)
- [Inversify](https://github.com/inversify/InversifyJS)
- [TSyringe](https://github.com/microsoft/tsyringe)
- [TypeDI](https://github.com/typestack/typedi)

Other resources:
- [JavaScript dependency injection in Node.js – friends or foes?](https://tsh.io/blog/dependency-injection-in-node-js/)

Acceptance criteria:
- It works in React Native and Electron

**Comment by DavidClawson** [comment]
Hey, Jakub!

James and I were discussing this after our last call, and dependency injection does look interesting. I looked into TSyringe a little, and it does seem like it could be a viable option. I specifically tried to find discussion that would disqualify some of the solutions you list, given the acceptance criteria. 

From what I've seen (I'm not an expert!), the DI container capability could also be interesting for the framework, as it could reduce some of the code that gets repeated so frequently.

**Comment by brianorwhatever** [comment]
I have been using nest.js after trying a few others (including inversify) and found it to be the best, but I'll admit I might be biased as I liked a few other nest.js features

**Comment by JamesKEbert** [comment]
I think the addition of Dependency Injection to the framework would be quite beneficial, for both internal structuring/dependencies but also the flexibility it would offer from the plugability perspective.

My thoughts on specific solutions after some research on each:

I think NestJS is not likely viable due to it being server-side specific implementation/goals. Even if for just dependency injection we'd be tying ourselves to a solution that does not guarantee React Native or Electron support into the future.

> Nest (NestJS) is a framework for building efficient, scalable Node.js server-side applications

Awilix does not appear to support React Native out of the box -- however I could be wrong on this front, but I wasn't able to find anything so far.

With TypeDI I wasn't able to find good sources for using within React Native (potentially possible, but I didn't see any examples or claims as such).

\
\
TSyringe - wasn't specifically called out as supporting React Native -- however this [Github issue](https://github.com/microsoft/tsyringe/issues/124) would indicate it is possible. So, this could be a viable path. Portions of their API are appealing.

InversifyJS - They claim framework agnostic support, and I think they have a wide variety of tools to help address our needs. 
> Inversifyjs is framework-agnostic

So, ultimately I am leaning towards InversifyJS, however I am open to other options! Especially in actually working to utilize a solution it may become obvious a pivot in approach is necessary.

**Comment by TimoGlastra** [comment]
It seems like InversifyJS also has some problems with RN:

- https://github.com/inversify/InversifyJS/issues/1050
- https://github.com/inversify/InversifyJS/issues/1007#issuecomment-556866192
- https://github.com/inversify/InversifyJS/issues/1113#issuecomment-531819266

All are old issues, but none are closed. So it doesn't seem very framework-agnostic. (maybe it's framework agnostic, just not environment agnostic)

The comments mention using `babel-plugin-transform-typescript-metadata` to solve this issue.

I see TSyringe also added the same to their readme 17 hours ago, explicitly mentioning React Native:

https://github.com/microsoft/tsyringe#babel

I'm a bit unclear on how this would work if we consume AFJ from react native. We don't use Babel for AFJ, but we do use babel in React Native. But the react native bundler will consume the already compiled TS (so JS). So `babel-plugin-transform-typescript-metadata` won't be of much help on the AFJ or RN side. Only if you use the source AFJ TS files in RN

**Comment by TimoGlastra** [comment]
Welp, I commented before reading.

The TS compiler already manages this correctly using the `experimentalDecorators` and `emitDecoratorMetadata` flags. So no problem here.

So the `babel-plugin-transform-typescript-metadata` plugin will only be required in RN projects if you use any of the DI functionality that wasn't already in AFJ (e.g. create a new service that needs injection).

Seems reasonable and not something we can work around.

**Comment by TimoGlastra** [comment]
Based on this my preferences would go to either InversifyJS or TSyringe with a preference to TSyringe for the following reasons:

- Created by Microsoft
- Small
- Explicitly mentions React Native in their Readme
