### ISSUE TITLE
Supporting multiple genesis file

### ISSUE THREAD

**Issue by MosCD3** [hyperledger/aries-framework-javascript#395]
In the .net version of Aries framework the wallet initialized with several pools created 
this what happens when initializing the agent

 private Dictionary<string, string> poolConfigs = new Dictionary<string, string>
        {
            { "sovrin-staging", "pool_transactions_sandbox_genesis" },
            { "sovrin-live", "pool_transactions_live_genesis" },
            { "sovrin-builder", "pool_transactions_builder_genesis" },
            { "bcovrin-test", "pool_transactions_bcovrin_test_genesis" }
        };

and the in a for loop
//code for downloading each genesis
//then
await poolService.CreatePoolAsync(config.Key, filename)
                        .ConfigureAwait(false);

and then you can use the wallet with all those networks 
the problem with one genesis file is guessing which file will work with which 

trying to test with 'https://studio.trinsic.id/' but not sure which genesis to use so it would be good feature if the framework supports same init feature like the .net one

**Comment by TimoGlastra** [comment]
I agree we should add this. But I think there are different features here, where you're requesting one, while .NET has implemented the the other (AFAIK).

- Supporting multiple pools (relatively easy). You still need to provide which pool to use for each credential, as it doesn't automatically detect which pool to use for which credential. This is what .NET has implemented I believe.
- Automatically supporting multiple pools (hard). The framework automatically detects which credential belongs to which pool and uses that. This will be easy once `did:indy` is supported, but is hard right now. (See https://docs.google.com/document/d/109C_eMsuZnTnYe2OAd02jAts1vC4axwEKIq7_4dnNVA/edit?usp=sharing for more info)

**Comment by swcurran** [comment]
Hard or not -- it still needs to be done to be useful. You can't leave it to every controller to figure it out -- from experience with other features, that's not a viable solution (anoncreds revocation, endorser signing).  The Aries framework has to do the heavy lifting so that the controller's job is easy (as can be).  There could be a webhook/admin api endpoint to allow the controller to participate in the choice of network when there is a conflict -- although I think there should be a "--auto..." option -- but the controller can't be left on it's own to figure out checking multiple networks.
