### ISSUE TITLE
Present revoked credential and it shows as verified successfully

### ISSUE THREAD

**Issue by standlove** [hyperledger/aries-framework-javascript#693]
Hi,

When using 0.1.0, we can present revoked credential to the proof request, and it shows as verification succeeded too. While it should show as verification failed. (like in trinsic app)

Is this feature supported in the current version?  

Thanks.

**Comment by TimoGlastra** [comment]
Hi @standlove, revocation support has only been added since version [v0.2.0-alpha.20](https://github.com/hyperledger/aries-framework-javascript/releases/tag/v0.2.0-alpha.20). Could you try to use the alpha version of AFJ and see if this issue still persists?

I would have guessed it would blow up if receiving a revocable cred before that release but it seems it just silently ignores it.

**Comment by standlove** [comment]
Hi,  @TimoGlastra 

Yes, I tried [v0.2.0-alpha.39](https://github.com/hyperledger/aries-framework-javascript/releases/tag/v0.2.0-alpha.39) too, and in this version, the revoked credential won't be matched to the proof request. Is it the expected behavior? 

While in the trinsic app, the revoked credential is matched.  Thanks.

**Comment by TimoGlastra** [comment]
Yes, by default this parameter is set to true: https://github.com/hyperledger/aries-framework-javascript/blob/main/packages/core/src/modules/proofs/ProofsModule.ts#L485

If you don't use auto accept you can pass this parameter to the `getRequestedCredentialsForProofRequest` method

**Comment by sheraliinamdar** [comment]
Hi @TimoGlastra ,
  any guess when this 0.2.0 AFJ stable version is getting released ?

**Comment by TimoGlastra** [comment]
I hope soon. There's still some PRs to be merged, but once merged we'll make the release ASAP.

See here for the overview of outstanding tasks for the 0.2.0 release: https://github.com/hyperledger/aries-framework-javascript/discussions/622
