### ISSUE TITLE
Credential offer and Proof requests sent while the app is closed are not received when re-open the app

### ISSUE THREAD

**Issue by standlove** [hyperledger/aries-framework-javascript#708]
Hi,

Here are the steps
- Put the app into the background or closed
- Send the Credential offer and Proof requests to the app
- Reopen the app, but the sent credential and proof requests in last step are not received. 

How is this handled in the aries framework?  Or is this handled in the mediator server? 

Thanks.

**Comment by TimoGlastra** [comment]
The mediator should store the messages until the app is reopened and able to receive the messages. Are you using ACA-Py as a mediator?  Have you set the mediator as default mediator in AFJ?

**Comment by TimoGlastra** [comment]
Yes if all is well, it should automatically reconnect and retrieve the pending messages.

The `MEDIATOR_URL` is an invitation url from ACA-Py or the actual URL of the mediator (it should be the former, not the latter)

If it's not working for you, could you set the log level to debug and share the logs with me, both before and after you close/reopen the app?

**Comment by standlove** [comment]
Yes, the MEDIATOR_URL is an invitation from ACA-Py. 

Here is the messages before I close the app.  I sent a proof request, it's received. 
[before-close-app.txt](https://github.com/hyperledger/aries-framework-javascript/files/8489779/before-close-app.txt)

Then I close the app, and send another proof request, reopen the app.  The sent proof request is not received:
[after-reopen-app.txt](https://github.com/hyperledger/aries-framework-javascript/files/8489778/after-reopen-app.txt)

Thanks.

**Comment by TimoGlastra** [comment]
Hmm looking at the logs everything is working as it should be, so I'm leaning towards this being an issue with the mediator. 

Have you enabled the --enable-undelivered-queue option in the ACA-Py mediator?

**Comment by standlove** [comment]
Hi, @TimoGlastra 

Thanks, the messages are received now after adding this option to the mediator. 

But there is another issue. 

If I sent two messages (1 credential and 1 proof request) while the app is closed, after I reopen the app. only one message is received, I need to reopen the app again to receive the other one. 

Any idea about this?  Thanks.

**Comment by TimoGlastra** [comment]
Yes we're also experiencing this issue. I think it has something to do with ACA-Py's queueing logic.

I'll try to take a look and see what's the issue, however I think this will be solved using the pickup v2 protocol which makes everything a lot more explicit. There's a plugin for ACA-Py: https://github.com/Indicio-tech/acapy-plugin-pickup and an open PR for AFJ: https://github.com/hyperledger/aries-framework-javascript/pull/711 so maybe we'll focus on that approach instead of fixing the current approach

**Comment by JamesKEbert** [comment]
Yeah I can confirm the way ACA-Py's logic is working that we can only retrieve **one** message from the mediator (ACA-Py) on launch as we only send one trust ping. We _could_ send additional trust pings, however we have no idea whether or not an inbound message was in response to a trust ping or just streamed down over the WS, which could lead to some really odd behavior that would be _really_ hard to reproduce. 
So, @TimoGlastra is right in that this issue is exactly what motivated and enabled us to implement pickup v2. Pickup v2 comes with a lot of other awesome benefits, but this is specifically what allowed us to do the development here. So, this issue should be resolved with #711 once merged.

**Comment by swcurran** [comment]
Could you please do a write up issue about what’s needed in ACA-Py?

**Comment by JamesKEbert** [comment]
Yeah I'd happy to write that up with @dbluhm! 👍

**Comment by standlove** [comment]
After adding the --enable-undelivered-queue option to the mediator. 

The app is unable to get the messages after some time:
```
 WARN  Possible Unhandled Promise Rejection (id: 0):
[TimeoutError: Timeout has occurred]
```

The backend log is attached below:
[MediatorErrorStack.txt](https://github.com/hyperledger/aries-framework-javascript/files/8514000/MediatorErrorStack.txt)

Any idea about this?  Thanks.

**Comment by TimoGlastra** [comment]
This issue can be fixed by using the pickup v2 protocol, closing this ticket, please open a new ticket if you're still running into problems
