### ISSUE TITLE
Integration with rn-indy-sdk

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#87]
[rn-indy-sdk](https://github.com/AbsaOSS/rn-indy-sdk) is an implementation of the indy-sdk that matches the API of the [NodeJS Wrapper](https://github.com/hyperledger/indy-sdk/tree/master/wrappers/nodejs).

We should add support and documentation to use Aries Framework JavaScript in a React Native application.

- [ ] Add documentation on how to use the framework with RN Indy SDK
- [ ] Run tests with RN Indy SDK?
- [x] Document packages and globals that are native to NodeJS and need special handling when using RN
    - buffer → https://www.npmjs.com/package/buffer
    - events → https://www.npmjs.com/package/events
    - base64 → https://www.npmjs.com/package/base64url (#95)

**Comment by TheArhaam** [comment]
@TimoGlastra Has there been any progress on this? I have imported `aries-framework-javascript` into my `react-native` app but since there isn't any example I can refer to I'm having trouble figuring it out.

At first, I faced issues where `aries-framework-javascript` couldn't find certain modules. Installing those modules seemed to have helped but can't be certain until I get the Agent up and running.

The issue I am currently facing is with the `InboundTransporter` & `OutboundTransporter`. I am not sure how to initialize these and they are a requirement for initializing the `Agent` so I was wondering if there is an example for `react-native` where at least all the initializations are taken care of.
