### ISSUE TITLE
credential exchange record is broken for V1 and V2

### ISSUE THREAD

**Issue by Amit-Padmani** [hyperledger/aries-framework-javascript#891]
I found the different between V1 and V2 credential exchange record in the latest version of AFJ. In V2 credential record I am not receiving the `credentialAttributes`, Also in V1 credential record I am not getting the schema id and credential definition id which was initially present into the `metadata` of the credential record .

I am using the below version of AFJ
"@aries-framework/core": "0.2.0-alpha.133",
"@aries-framework/react-native": "0.2.0-alpha.133"

Credential exchange record 
[AFJ cred exchange record.log](https://github.com/hyperledger/aries-framework-javascript/files/8941761/AFJ.cred.exchange.record.log)

**Comment by TimoGlastra** [comment]
Hi @Amit-Padmani it is expected the attributes are not stored on the record anymore since a recent PR. We only store the attributes / metadata in the record after you've accepted the offer. It is weird however that the v1 record does have the attributes, and I've created a PR to fix this: #892

This doesn't solve your issue however. For that, please see the following section in the update documentation on where you can now find these value when the credential hasn't state `Done` yet: https://github.com/animo/aries-javascript-docs/blob/main/guides/updating/versions/0.1-to-0.2.md#data-from-received-messages-only-stored-in-record-after-accepting
