### ISSUE TITLE
Fix flaky tests that start event listener after performing an action

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#894]
We only start event listeners after an actions has been performed (sendProposal -> start proposal received listener) in most e2e tests, while we should be starting the listener before performing the action (start proposal received listener -> sendProposal) to prevent flaky tests.

I've fixed it for one file as example (#893 ), but we should look at all ICv2 and PPv2 tests (that's where we use evens A LOT).

**Comment by 2byrds** [comment]
Timo started this work here: https://github.com/hyperledger/aries-framework-javascript/pull/893/files
I learned from that and added more ICv2 tests here: https://github.com/hyperledger/aries-framework-javascript/pull/966
We'll tackle PPv2 tests in another PR since that module has changed significantly.
